version: '3.4'

services:
  roomservicemanagement.api:
    image: roomservicemanagement:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "RoomServiceManagement.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_roomservicemanagement.api$
    volumes:
      - C:\Users\j.olive\source\repos\UOCHotels\RoomServiceManagement.Api:/app
      - C:\Users\j.olive\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_roomservicemanagement.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_roomservicemanagement.api$ \"bin/Debug/netcoreapp2.2/RoomServiceManagement.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
